import { StyleSheet } from 'react-native';
import { COLORES } from '../estilos/colores';
import { FUENTE, ESPACIADO, RADIO } from '../estilos/tema';

export const estilos = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: COLORES.fondo },
  scroll: { padding: ESPACIADO.md, paddingBottom: ESPACIADO.xxl },

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: ESPACIADO.sm,
    marginBottom: ESPACIADO.lg,
  },
  fechaTexto: {
    fontSize: FUENTE.tamanoPequeno,
    color: COLORES.textoSecundario,
    textTransform: 'capitalize',
    marginBottom: 2,
  },
  titulo: {
    fontSize: FUENTE.tamanoXl,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.texto,
    letterSpacing: -0.5,
  },
  avatarBox: {
    width: 46,
    height: 46,
    borderRadius: RADIO.md,
    backgroundColor: COLORES.primarioClaro,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ─── Ganancia card ────────────────────────────────────────────────────────
  gananciaCard: {
    borderRadius: RADIO.xl,
    padding: ESPACIADO.lg,
    marginBottom: ESPACIADO.md,
  },
  gananciaTitulo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: ESPACIADO.sm,
  },
  gananciaTituloLeft: { gap: 5 },
  gananciaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: RADIO.full,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
  },
  gananciaBadgeTexto: { fontSize: FUENTE.tamanoXs, color: COLORES.blanco, fontWeight: FUENTE.pesoSemibold },
  gananciaEtiqueta: { fontSize: FUENTE.tamanoPequeno, color: 'rgba(255,255,255,0.8)' },
  gananciaInfoBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gananciaValor: {
    fontSize: 36,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.blanco,
    letterSpacing: -1.5,
    marginBottom: ESPACIADO.md,
  },
  gananciaDivider: { height: 1, backgroundColor: 'rgba(255,255,255,0.2)', marginBottom: ESPACIADO.md },
  gananciaDesglose: { flexDirection: 'row', alignItems: 'center' },
  gananciaItem: { flex: 1, alignItems: 'center', gap: 3 },
  gananciaItemLabel: { fontSize: FUENTE.tamanoXs, color: 'rgba(255,255,255,0.75)' },
  gananciaItemValor: { fontSize: FUENTE.tamanoPequeno, fontWeight: FUENTE.pesoBold, color: COLORES.blanco },
  gananciaItemSep: { width: 1, height: 28, backgroundColor: 'rgba(255,255,255,0.2)' },
  gananciaFooter: {
    marginTop: ESPACIADO.sm,
    paddingTop: ESPACIADO.sm,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.15)',
  },
  gananciaFooterTexto: { fontSize: FUENTE.tamanoXs, color: 'rgba(255,255,255,0.7)', textAlign: 'center' },

  // ─── Barras por mes ───────────────────────────────────────────────────────
  barrasScroll: { marginBottom: ESPACIADO.md, marginHorizontal: -ESPACIADO.md },
  barraCard: {
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.lg,
    padding: ESPACIADO.sm,
    alignItems: 'center',
    minWidth: 72,
    borderWidth: 1.5,
    borderColor: COLORES.borde,
  },
  barraCardActual: { borderColor: COLORES.primario, backgroundColor: COLORES.primarioClaro },
  barraMes: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario, fontWeight: FUENTE.pesoSemibold, marginBottom: 4 },
  barraMesActual: { color: COLORES.primario },
  barraValor: { fontSize: FUENTE.tamanoXs, fontWeight: FUENTE.pesoBold, marginBottom: 5 },
  barraIndicador: { width: 20, height: 3, borderRadius: 2 },

  // ─── Total histórico ──────────────────────────────────────────────────────
  totalHistCard: {
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.md,
    marginBottom: ESPACIADO.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 1,
  },
  totalHistFila: { flexDirection: 'row', alignItems: 'center' },
  totalHistItem: { flex: 1, alignItems: 'center', gap: 4, paddingVertical: ESPACIADO.xs },
  totalHistLabel: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario, textAlign: 'center' },
  totalHistValor: { fontSize: FUENTE.tamanoPequeno, fontWeight: FUENTE.pesoBold, textAlign: 'center' },
  totalHistSep: { width: 1, height: 40, backgroundColor: COLORES.borde },

  // ─── Sección títulos ──────────────────────────────────────────────────────
  seccionTituloFila: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: ESPACIADO.sm,
  },
  seccionTitulo: {
    fontSize: FUENTE.tamanoBase,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.texto,
    marginTop: ESPACIADO.xs,
    marginBottom: ESPACIADO.sm,
  },
  verTodos: { fontSize: FUENTE.tamanoPequeno, color: COLORES.primario, fontWeight: FUENTE.pesoSemibold },

  // ─── Tarjetas financieras ─────────────────────────────────────────────────
  gridDos: { flexDirection: 'row', gap: ESPACIADO.sm, marginBottom: ESPACIADO.sm },
  tarjeta: {
    flex: 1,
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  tarjetaIconBox: {
    width: 36,
    height: 36,
    borderRadius: RADIO.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: ESPACIADO.sm,
  },
  tarjetaValor: {
    fontSize: FUENTE.tamanoMedio,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.texto,
    letterSpacing: -0.3,
    marginBottom: 1,
  },
  tarjetaTitulo: { fontSize: FUENTE.tamanoPequeno, fontWeight: FUENTE.pesoSemibold, color: COLORES.texto, marginBottom: 1 },
  tarjetaSubtitulo: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario },

  // ─── Acciones rápidas ─────────────────────────────────────────────────────
  accionesGrid: { flexDirection: 'row', gap: ESPACIADO.sm, marginBottom: ESPACIADO.sm },
  accion: {
    flex: 1,
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.md,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 1,
  },
  accionIconBox: {
    width: 50,
    height: 50,
    borderRadius: RADIO.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: ESPACIADO.sm,
  },
  accionTitulo: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold, color: COLORES.texto, marginBottom: 2 },
  accionDesc: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario, textAlign: 'center' },

  // ─── Pedidos pendientes ───────────────────────────────────────────────────
  itemPendiente: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.md,
    marginBottom: ESPACIADO.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 1,
  },
  pendIconBox: {
    width: 40,
    height: 40,
    borderRadius: RADIO.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: ESPACIADO.sm,
  },
  pendInfo: { flex: 1 },
  pendPersona: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoSemibold, color: COLORES.texto },
  pendFecha: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario, marginTop: 2 },
  pendDer: { alignItems: 'flex-end', gap: 3, marginRight: 2 },
  pendSaldo: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold, color: COLORES.pendiente },

  // ─── Crédito desarrollador ────────────────────────────────────────────────
  creditoBox: {
    alignItems: 'center',
    paddingVertical: ESPACIADO.lg,
    paddingBottom: ESPACIADO.xl,
  },
  creditoTexto: {
    fontSize: 11,
    color: COLORES.textoDeshabilitado,
    letterSpacing: 0.3,
  },
});
