import { StyleSheet } from 'react-native';
import { COLORES } from '../estilos/colores';
import { FUENTE, ESPACIADO, RADIO } from '../estilos/tema';

export const estilos = StyleSheet.create({
  /** El color de fondo lo define `estilosFondoAtmosfera.safeArea` en la pantalla. */
  contenedor: { flex: 1 },
  scroll: { padding: ESPACIADO.md, paddingBottom: ESPACIADO.xxl },

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: ESPACIADO.sm,
    marginBottom: ESPACIADO.lg,
  },
  fechaTexto: {
    fontSize: FUENTE.tamanoPequeno,
    color: COLORES.textoSecundario,
    textTransform: 'capitalize',
    marginBottom: 2,
  },
  titulo: {
    fontSize: FUENTE.tamanoXl,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.texto,
    letterSpacing: -0.5,
  },
  avatarBox: {
    width: 46,
    height: 46,
    borderRadius: RADIO.md,
    backgroundColor: COLORES.primarioClaro,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ─── Ganancia card ────────────────────────────────────────────────────────
  gananciaCard: {
    borderRadius: RADIO.xl,
    padding: ESPACIADO.lg,
    marginBottom: ESPACIADO.md,
  },
  gananciaTitulo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: ESPACIADO.sm,
  },
  gananciaTituloLeft: { flex: 1, minWidth: 0, gap: 5 },
  gananciaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: RADIO.full,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
  },
  gananciaBadgeTexto: { fontSize: FUENTE.tamanoXs, color: COLORES.blanco, fontWeight: FUENTE.pesoSemibold },
  gananciaEtiqueta: { fontSize: FUENTE.tamanoPequeno, color: 'rgba(255,255,255,0.8)' },
  gananciaInfoBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gananciaValor: {
    alignSelf: 'stretch',
    fontSize: 36,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.blanco,
    letterSpacing: -1.5,
    marginBottom: ESPACIADO.sm,
  },
  gananciaNetaSplit: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginBottom: ESPACIADO.md,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: RADIO.lg,
    paddingVertical: ESPACIADO.sm,
    paddingHorizontal: ESPACIADO.xs,
  },
  gananciaNetaSplitCol: { flex: 1, minWidth: 0, alignItems: 'center', gap: 4, paddingHorizontal: 4 },
  gananciaNetaSplitSep: { width: 1, backgroundColor: 'rgba(255,255,255,0.25)', alignSelf: 'stretch' },
  gananciaNetaSplitTitulo: {
    fontSize: 10,
    fontWeight: FUENTE.pesoBold,
    color: 'rgba(255,255,255,0.85)',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  gananciaNetaSplitMonto: { fontSize: FUENTE.tamanoPequeno, fontWeight: FUENTE.pesoBold, color: COLORES.blanco },
  gananciaNetaSplitIngresos: {
    fontSize: 9,
    color: 'rgba(255,255,255,0.6)',
    textAlign: 'center',
    marginTop: 2,
  },
  gananciaDivider: { height: 1, backgroundColor: 'rgba(255,255,255,0.2)', marginBottom: ESPACIADO.md },
  gananciaDesglose: { flexDirection: 'row', alignItems: 'center' },
  gananciaItem: { flex: 1, minWidth: 0, alignItems: 'center', gap: 3 },
  gananciaItemLabel: {
    fontSize: FUENTE.tamanoXs,
    color: 'rgba(255,255,255,0.75)',
    textAlign: 'center',
  },
  gananciaItemValor: { fontSize: FUENTE.tamanoPequeno, fontWeight: FUENTE.pesoBold, color: COLORES.blanco },
  gananciaItemSep: { width: 1, height: 28, backgroundColor: 'rgba(255,255,255,0.2)' },
  gananciaFooter: {
    marginTop: ESPACIADO.sm,
    paddingTop: ESPACIADO.sm,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.15)',
  },
  gananciaFooterTexto: { fontSize: FUENTE.tamanoXs, color: 'rgba(255,255,255,0.7)', textAlign: 'center' },
  gananciaTocarHint: {
    marginTop: ESPACIADO.sm,
    fontSize: 10,
    color: 'rgba(255,255,255,0.55)',
    textAlign: 'center',
    fontWeight: FUENTE.pesoSemibold,
  },

  // ─── Barras por mes ───────────────────────────────────────────────────────
  barrasScroll: { marginBottom: ESPACIADO.md, marginHorizontal: -ESPACIADO.md },
  barraCard: {
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.lg,
    padding: ESPACIADO.sm,
    alignItems: 'center',
    minWidth: 72,
    borderWidth: 1.5,
    borderColor: COLORES.borde,
  },
  barraCardActual: { borderColor: COLORES.primario, backgroundColor: COLORES.primarioClaro },
  barraMes: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario, fontWeight: FUENTE.pesoSemibold, marginBottom: 4 },
  barraMesActual: { color: COLORES.primario },
  barraValor: { fontSize: FUENTE.tamanoXs, fontWeight: FUENTE.pesoBold, marginBottom: 3 },
  barraIva: {
    fontSize: 10,
    color: COLORES.textoSecundario,
    fontWeight: FUENTE.pesoSemibold,
    marginBottom: 4,
    textAlign: 'center',
  },
  barraIndicador: { width: 20, height: 3, borderRadius: 2 },

  // ─── Total histórico (cuadrícula tipo mini-tarjetas) ───────────────────────
  totalHistCard: {
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.lg,
    marginBottom: ESPACIADO.lg,
    borderWidth: 1,
    borderColor: COLORES.bordeOscuro,
    shadowColor: '#1e1b4b',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.09,
    shadowRadius: 20,
    elevation: 5,
  },
  totalHistHeader: { alignItems: 'center', marginBottom: ESPACIADO.md },
  totalHistEncabezado: {
    fontSize: FUENTE.tamanoGrande,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.texto,
    textAlign: 'center',
    letterSpacing: -0.45,
    marginBottom: ESPACIADO.sm,
  },
  totalHistPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORES.primarioClaro,
    paddingHorizontal: ESPACIADO.md,
    paddingVertical: 6,
    borderRadius: RADIO.full,
    borderWidth: 1,
    borderColor: 'rgba(79, 70, 229, 0.18)',
  },
  totalHistPillTxt: {
    fontSize: FUENTE.tamanoPequeno,
    fontWeight: FUENTE.pesoSemibold,
    color: COLORES.primarioOscuro,
  },
  totalHistGrid: { gap: ESPACIADO.sm },
  totalHistFilaGrid: { flexDirection: 'row', gap: ESPACIADO.sm, alignItems: 'stretch' },
  totalHistTile: {
    flex: 1,
    minWidth: 0,
    borderRadius: RADIO.lg,
    padding: ESPACIADO.sm,
    minHeight: 120,
    borderWidth: 1,
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  totalHistIconBubble: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: ESPACIADO.sm,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  totalHistTileTitulo: {
    fontSize: FUENTE.tamanoBase,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.texto,
    letterSpacing: -0.2,
  },
  totalHistTileHist: {
    fontSize: 10,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.textoSecundario,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    marginTop: 3,
    marginBottom: ESPACIADO.xs,
  },
  totalHistTileValor: {
    fontSize: FUENTE.tamanoMedio,
    fontWeight: FUENTE.pesoBold,
    letterSpacing: -0.35,
    marginTop: ESPACIADO.xs,
    alignSelf: 'stretch',
    lineHeight: 22,
    flexShrink: 1,
  },
  totalHistAyuda: {
    fontSize: FUENTE.tamanoXs,
    color: COLORES.textoSecundario,
    textAlign: 'center',
    lineHeight: 17,
    marginTop: 4,
    paddingHorizontal: ESPACIADO.sm,
  },
  totalHistPieHint: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
    marginTop: ESPACIADO.sm,
    paddingTop: ESPACIADO.md,
    borderTopWidth: 1,
    borderTopColor: COLORES.borde,
  },
  totalHistPieHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  totalHistPieHintTxt: {
    fontSize: FUENTE.tamanoPequeno,
    fontWeight: FUENTE.pesoSemibold,
    color: COLORES.primarioOscuro,
  },

  // ─── Sección títulos ──────────────────────────────────────────────────────
  seccionTituloFila: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: ESPACIADO.sm,
    minWidth: 0,
    gap: ESPACIADO.sm,
  },
  /** Título a la izquierda en `seccionTituloFila`: encoge en pantallas angostas sin empujar «Ver todos». */
  seccionTituloEnFila: {
    flex: 1,
    minWidth: 0,
  },
  seccionTitulo: {
    fontSize: FUENTE.tamanoBase,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.texto,
    marginTop: ESPACIADO.xs,
    marginBottom: ESPACIADO.sm,
  },
  verTodos: { fontSize: FUENTE.tamanoPequeno, color: COLORES.primario, fontWeight: FUENTE.pesoSemibold },

  // ─── Tarjetas financieras ─────────────────────────────────────────────────
  gridDos: { flexDirection: 'row', gap: ESPACIADO.sm, marginBottom: ESPACIADO.sm },
  tarjeta: {
    flex: 1,
    minWidth: 0,
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  tarjetaIconBox: {
    width: 36,
    height: 36,
    borderRadius: RADIO.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: ESPACIADO.sm,
  },
  tarjetaValor: {
    fontSize: FUENTE.tamanoMedio,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.texto,
    letterSpacing: -0.3,
    marginBottom: 1,
  },
  tarjetaTitulo: { fontSize: FUENTE.tamanoPequeno, fontWeight: FUENTE.pesoSemibold, color: COLORES.texto, marginBottom: 1 },
  tarjetaSubtitulo: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario },

  // ─── Acciones rápidas ─────────────────────────────────────────────────────
  accionesGrid: { flexDirection: 'row', gap: ESPACIADO.sm, marginBottom: ESPACIADO.sm },
  accion: {
    flex: 1,
    minWidth: 0,
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.md,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 1,
  },
  accionIconBox: {
    width: 50,
    height: 50,
    borderRadius: RADIO.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: ESPACIADO.sm,
  },
  accionTitulo: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold, color: COLORES.texto, marginBottom: 2 },
  accionDesc: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario, textAlign: 'center' },

  // ─── Pedidos pendientes ───────────────────────────────────────────────────
  itemPendiente: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.md,
    marginBottom: ESPACIADO.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 1,
  },
  pendIconBox: {
    width: 40,
    height: 40,
    borderRadius: RADIO.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: ESPACIADO.sm,
  },
  pendInfo: { flex: 1, minWidth: 0 },
  pendPersona: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoSemibold, color: COLORES.texto },
  pendCliente: {
    fontSize: FUENTE.tamanoXs,
    fontWeight: FUENTE.pesoMedio,
    color: COLORES.texto,
    marginTop: 2,
  },
  pendFecha: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario, marginTop: 2 },
  pendDer: { alignItems: 'flex-end', gap: 3, marginRight: 2 },
  pendSaldo: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold, color: COLORES.pendiente },

  /** Tarjeta «Resumen por periodo»: mismo lenguaje visual que gananciaCard / «Este mes». */
  accesoResumenPeriodoHero: {
    fontSize: FUENTE.tamanoGrande,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.blanco,
    letterSpacing: -0.4,
    marginTop: 2,
  },
  accesoResumenPeriodoSubBlanco: {
    fontSize: FUENTE.tamanoPequeno,
    color: 'rgba(255,255,255,0.82)',
    marginTop: ESPACIADO.sm,
    lineHeight: 18,
  },

  // ─── Crédito desarrollador ────────────────────────────────────────────────
  creditoBox: {
    alignItems: 'center',
    paddingVertical: ESPACIADO.lg,
    paddingBottom: ESPACIADO.xl,
  },
  creditoTexto: {
    fontSize: 11,
    color: COLORES.textoDeshabilitado,
    letterSpacing: 0.3,
  },
});
