import { StyleSheet } from 'react-native';
import { COLORES } from '../../estilos/colores';
import { FUENTE, ESPACIADO, RADIO } from '../../estilos/tema';

export const estilos = StyleSheet.create({
  scroll: { padding: ESPACIADO.md, paddingBottom: ESPACIADO.xl },
  etiqueta: {
    fontSize: FUENTE.tamanoPequeno,
    fontWeight: FUENTE.pesoSemibold,
    color: COLORES.textoSecundario,
    marginBottom: ESPACIADO.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  selectorPersona: {
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.lg,
    borderWidth: 1.5,
    borderColor: COLORES.borde,
    marginBottom: ESPACIADO.md,
    overflow: 'hidden',
  },
  selectorPersonaVacio: {
    borderStyle: 'dashed',
  },
  personaSeleccionada: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: ESPACIADO.md,
    gap: ESPACIADO.sm,
  },
  personaPlaceholder: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: ESPACIADO.md,
    gap: ESPACIADO.sm,
  },
  placeholderIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORES.grisClaro,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderTexto: {
    flex: 1,
    color: COLORES.textoDeshabilitado,
    fontSize: FUENTE.tamanoBase,
  },
  avatarPequeno: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLetra: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold },
  personaNombre: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoSemibold, color: COLORES.texto },
  personaTipo: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario, marginTop: 2 },
  cambiarBtn: {
    backgroundColor: COLORES.grisClaro,
    borderRadius: RADIO.full,
    paddingVertical: 4,
    paddingHorizontal: ESPACIADO.sm,
  },
  cambiarTexto: { fontSize: FUENTE.tamanoXs, color: COLORES.textoSecundario, fontWeight: FUENTE.pesoMedio },
  seccionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: ESPACIADO.xs,
    marginTop: ESPACIADO.sm,
  },
  itemsContador: { fontSize: FUENTE.tamanoPequeno, color: COLORES.textoSecundario },
  itemCard: {
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.md,
    marginBottom: ESPACIADO.md,
    borderWidth: 1,
    borderColor: COLORES.borde,
  },
  itemCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: ESPACIADO.md,
  },
  itemNumeroBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORES.primarioClaro,
    borderRadius: RADIO.sm,
    paddingVertical: 4,
    paddingHorizontal: ESPACIADO.sm,
  },
  itemNumero: { fontSize: FUENTE.tamanoPequeno, fontWeight: FUENTE.pesoBold, color: COLORES.primario },
  eliminarBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORES.peligroClaro,
    borderRadius: RADIO.sm,
    paddingVertical: 4,
    paddingHorizontal: ESPACIADO.sm,
  },
  eliminarTexto: { fontSize: FUENTE.tamanoPequeno, color: COLORES.peligro },
  filaInputs: { flexDirection: 'row' },
  botonAgregarItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: ESPACIADO.sm,
    borderWidth: 1.5,
    borderColor: COLORES.primario,
    borderStyle: 'dashed',
    borderRadius: RADIO.lg,
    paddingVertical: ESPACIADO.md,
    marginBottom: ESPACIADO.lg,
    backgroundColor: COLORES.primarioClaro,
  },
  botonAgregarItemTexto: { color: COLORES.primario, fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold },
  togglePago: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ESPACIADO.sm,
    marginBottom: ESPACIADO.md,
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.lg,
    padding: ESPACIADO.md,
    borderWidth: 1,
    borderColor: COLORES.borde,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: COLORES.bordeOscuro,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORES.grisClaro,
  },
  checkboxActivo: { backgroundColor: COLORES.primario, borderColor: COLORES.primario },
  togglePagoTitulo: { fontSize: FUENTE.tamanoBase, color: COLORES.texto, fontWeight: FUENTE.pesoMedio },
  footer: {
    padding: ESPACIADO.md,
    backgroundColor: COLORES.fondo,
    borderTopWidth: 1,
    borderTopColor: COLORES.borde,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: ESPACIADO.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORES.borde,
  },
  modalTitulo: { fontSize: FUENTE.tamanoMedio, fontWeight: FUENTE.pesoBold, color: COLORES.texto },
  modalSubtitulo: { fontSize: FUENTE.tamanoPequeno, color: COLORES.textoSecundario, marginTop: 2 },
  modalCerrarBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORES.grisClaro,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ESPACIADO.md,
    paddingVertical: ESPACIADO.md,
    paddingHorizontal: ESPACIADO.sm,
  },
});
