import { StyleSheet } from 'react-native';
import { COLORES } from '../../estilos/colores';
import { FUENTE, ESPACIADO, RADIO } from '../../estilos/tema';

export const estilos = StyleSheet.create({
  scroll: { paddingBottom: ESPACIADO.xxl },

  heroCard: {
    margin: ESPACIADO.md,
    marginBottom: ESPACIADO.sm,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.lg,
  },
  heroTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: ESPACIADO.md,
  },
  heroPersona: {
    fontSize: FUENTE.tamanoGrande,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.blanco,
    letterSpacing: -0.3,
    marginBottom: 6,
  },
  heroBadgesFila: { flexDirection: 'row', gap: ESPACIADO.xs },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: RADIO.full,
    paddingHorizontal: ESPACIADO.sm,
    paddingVertical: 3,
  },
  heroBadgeTexto: { fontSize: FUENTE.tamanoXs, fontWeight: FUENTE.pesoBold, color: COLORES.blanco },
  heroEstadoBox: { marginLeft: ESPACIADO.sm, flexShrink: 0 },

  heroMontoFila: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: ESPACIADO.sm,
  },
  heroLabel: {
    fontSize: FUENTE.tamanoPequeno,
    color: 'rgba(255,255,255,0.75)',
    marginBottom: 2,
  },
  heroMonto: {
    fontSize: FUENTE.tamanoXxl,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.blanco,
    letterSpacing: -1,
  },
  heroFechaBox: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 4 },
  heroFecha: { fontSize: FUENTE.tamanoXs, color: 'rgba(255,255,255,0.8)' },

  progresoWrapper: { marginTop: ESPACIADO.xs },
  progresoBar: {
    height: 6,
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 5,
  },
  progresoFill: {
    height: '100%',
    backgroundColor: COLORES.blanco,
    borderRadius: 3,
  },
  progresoTexto: { fontSize: FUENTE.tamanoXs, color: 'rgba(255,255,255,0.85)' },

  heroMetaDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.28)',
    marginTop: ESPACIADO.sm,
    marginBottom: ESPACIADO.md,
  },
  heroMetaNombreSection: {
    marginTop: 0,
    paddingTop: ESPACIADO.md,
    marginBottom: 0,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.22)',
  },
  /** Misma jerarquía visual que Total / Impuesto; sin flex para que no compita con el botón */
  heroMetaNombreEtiqueta: {
    fontSize: 10,
    fontWeight: FUENTE.pesoSemibold,
    color: 'rgba(255,255,255,0.65)',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: ESPACIADO.xs,
  },
  heroMetaNombreValorFila: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: ESPACIADO.sm,
  },
  heroMetaNombreTextoWrap: {
    flex: 1,
    minWidth: 0,
  },
  heroMetaNombreTexto: {
    fontSize: FUENTE.tamanoBase,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.blanco,
    lineHeight: 22,
  },
  /** Compacto al lado del texto editado, no en la fila del título */
  heroMetaEditBtnCompact: {
    padding: 8,
    borderRadius: RADIO.md,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: 1,
  },
  /** Un solo bloque integrado (montos + referencia): evita la sensación de dos tarjetas dentro del hero */
  heroMetaBloqueUnificado: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: RADIO.lg,
    padding: ESPACIADO.md,
    overflow: 'hidden',
  },
  /** Fila tipo comprobante: etiqueta izquierda, monto derecha */
  heroMetaResumenFila: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: ESPACIADO.md,
  },
  heroMetaResumenFilaSep: {
    marginTop: ESPACIADO.sm,
    paddingTop: ESPACIADO.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.22)',
  },
  heroMetaLabelResumen: {
    fontSize: 10,
    fontWeight: FUENTE.pesoSemibold,
    color: 'rgba(255,255,255,0.65)',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    flex: 1,
    flexShrink: 1,
    paddingRight: ESPACIADO.sm,
  },
  heroMetaValorWrap: {
    flexShrink: 0,
    alignItems: 'flex-end',
    maxWidth: '58%',
  },
  heroMetaTotalPrincipal: {
    fontSize: FUENTE.tamanoGrande,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.blanco,
    textAlign: 'right',
  },
  heroMetaImpuestoValor: {
    fontSize: FUENTE.tamanoGrande,
    fontWeight: FUENTE.pesoBold,
    color: COLORES.blanco,
    textAlign: 'right',
  },
  heroMetaSinImpuesto: {
    fontSize: FUENTE.tamanoPequeno,
    fontWeight: FUENTE.pesoSemibold,
    color: 'rgba(255,255,255,0.88)',
    textAlign: 'right',
  },

  card: {
    backgroundColor: COLORES.tarjeta,
    borderRadius: RADIO.xl,
    padding: ESPACIADO.md,
    marginHorizontal: ESPACIADO.md,
    marginBottom: ESPACIADO.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: ESPACIADO.sm,
  },
  cardTitulo: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold, color: COLORES.texto },
  cardCount: {
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORES.grisClaro,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  cardCountTexto: { fontSize: FUENTE.tamanoXs, fontWeight: FUENTE.pesoBold, color: COLORES.textoSecundario },

  itemFila: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: ESPACIADO.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORES.borde,
    gap: ESPACIADO.sm,
  },
  itemIconBox: {
    width: 30,
    height: 30,
    borderRadius: RADIO.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemInfo: { flex: 1, minWidth: 0 },
  itemNombre: {
    fontSize: FUENTE.tamanoBase,
    color: COLORES.texto,
    fontWeight: FUENTE.pesoMedio,
    flexShrink: 1,
  },
  itemMeta: { fontSize: FUENTE.tamanoPequeno, color: COLORES.textoSecundario, marginTop: 2 },
  itemSubtotal: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold, color: COLORES.texto },
  totalFila: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: ESPACIADO.sm,
    marginTop: ESPACIADO.xs,
    borderTopWidth: 1.5,
    borderTopColor: COLORES.borde,
  },
  totalEtiqueta: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold, color: COLORES.texto },
  totalValor: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold, color: COLORES.texto },

  sinDatosBox: { alignItems: 'center', paddingVertical: ESPACIADO.lg, gap: ESPACIADO.xs },
  sinDatos: { fontSize: FUENTE.tamanoBase, color: COLORES.textoSecundario },

  pagoFila: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: ESPACIADO.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORES.borde,
    gap: ESPACIADO.sm,
  },
  pagoIconBox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORES.exitoClaro,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pagoFecha: { flex: 1, minWidth: 0, fontSize: FUENTE.tamanoBase, color: COLORES.textoSecundario },
  pagoMonto: { fontSize: FUENTE.tamanoBase, fontWeight: FUENTE.pesoBold, color: COLORES.exito },

  botonEliminar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: ESPACIADO.xs,
    padding: ESPACIADO.md,
    marginHorizontal: ESPACIADO.md,
    marginBottom: ESPACIADO.xs,
  },
  botonEliminarTexto: { fontSize: FUENTE.tamanoPequeno, color: COLORES.peligro, fontWeight: FUENTE.pesoMedio },

  footer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'stretch',
    padding: ESPACIADO.md,
    backgroundColor: COLORES.fondo,
    borderTopWidth: 1,
    borderTopColor: COLORES.borde,
    gap: ESPACIADO.sm,
  },
  botonPagarHero: {
    flex: 1,
    flexGrow: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORES.exito,
    borderRadius: RADIO.lg,
    paddingVertical: ESPACIADO.md,
  },
  botonPagarHeroTexto: {
    flexShrink: 1,
    textAlign: 'center',
    color: COLORES.blanco,
    fontSize: FUENTE.tamanoBase,
    fontWeight: FUENTE.pesoBold,
  },
  pagadoBox: {
    flex: 1,
    flexGrow: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORES.exitoClaro,
    borderRadius: RADIO.lg,
    paddingVertical: ESPACIADO.md,
  },
  pagadoTexto: {
    flexShrink: 1,
    textAlign: 'center',
    color: COLORES.exito,
    fontSize: FUENTE.tamanoPequeno,
    fontWeight: FUENTE.pesoSemibold,
  },
  botonPDF: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORES.primarioClaro,
    borderRadius: RADIO.lg,
    paddingHorizontal: ESPACIADO.md,
    paddingVertical: ESPACIADO.md,
    minWidth: 0,
    flexShrink: 0,
    justifyContent: 'center',
  },
  botonPDFTexto: { fontSize: FUENTE.tamanoPequeno, color: COLORES.primario, fontWeight: FUENTE.pesoBold },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  modalContenido: {
    backgroundColor: COLORES.tarjeta,
    borderTopLeftRadius: RADIO.xxl,
    borderTopRightRadius: RADIO.xxl,
    padding: ESPACIADO.lg,
    paddingBottom: ESPACIADO.xxl,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORES.borde,
    alignSelf: 'center',
    marginBottom: ESPACIADO.lg,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ESPACIADO.md,
    marginBottom: ESPACIADO.lg,
  },
  modalIconBox: {
    width: 48,
    height: 48,
    borderRadius: RADIO.md,
    backgroundColor: COLORES.exitoClaro,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitulo: { fontSize: FUENTE.tamanoGrande, fontWeight: FUENTE.pesoBold, color: COLORES.texto },
  modalSubtitulo: { fontSize: FUENTE.tamanoPequeno, color: COLORES.textoSecundario, marginTop: 2 },
  modalBotones: { flexDirection: 'row', marginTop: ESPACIADO.xs },
});
